# Generated by Django 3.1.5 on 2021-01-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0002_remove_messageobject_acknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageobject',
            name='user',
        ),
    ]
