# Generated by Django 3.1.5 on 2021-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0003_remove_messageobject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='message_object',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
