# Generated by Django 3.1.5 on 2021-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0005_auto_20210126_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='message_object',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
